import logoAirbnb from "./logos/airbnb.svg";
import logoAirteam from "./logos/airteam.svg";
import logoArm from "./logos/arm.svg";
import logoAtlassian from "./logos/atlassian.svg";
import logoBarnardos from "./logos/barnardos.svg";
import logoBcg from "./logos/bcg.svg";
import logoCareship from "./logos/careship.svg";
import logoCodeForAmerica from "./logos/code-for-america.svg";
import logoCsiro from "./logos/csiro.svg";
import logoDeloitte from "./logos/deloitte.svg";
import logoElsevier from "./logos/elsevier.svg";
import logoEnigma from "./logos/enigma.svg";
import logoEsri from "./logos/esri.svg";
import logoFreshworks from "./logos/freshworks.svg";
import logoFtw from "./logos/ftw.svg";
import logoHarvard from "./logos/harvard.svg";
import logoHotelsCombined from "./logos/hotelscombined.svg";
import logoIbm from "./logos/ibm.svg";
import logoIdeo from "./logos/ideo.svg";
import logoKickstand from "./logos/kickstand.svg";
import logoMaersk from "./logos/maersk.svg";
import logoMonotype from "./logos/monotype.svg";
import logoMozilla from "./logos/mozilla.svg";
import logoNike from "./logos/nike.svg";
import logoNswGovernment from "./logos/nsw-government.svg";
import logoNubank from "./logos/nubank.svg";
import logoOcado from "./logos/ocado.svg";
import logoPearson from "./logos/pearson.svg";
import logoRemax from "./logos/remax.svg";
import logoRbs from "./logos/rbs.svg";
import logoRmit from "./logos/rmit.svg";
import logoSalesforce from "./logos/salesforce.svg";
import logoSchibsted from "./logos/schibsted.svg";
import logoScout24 from "./logos/scout24.svg";
import logoSeek from "./logos/seek.svg";
import logoShopify from "./logos/shopify.svg";
import logoSkillsoft from "./logos/skillsoft.svg";
import logoSpotify from "./logos/spotify.svg";
import logoUcSanDiego from "./logos/uc-san-diego.svg";
import logoUniqa from "./logos/uniqa.svg";
import logoWeightWatchers from "./logos/weightwatchers.svg";
import logoWestpac from "./logos/westpac.svg";
import logoWework from "./logos/wework.svg";
import logoZillow from "./logos/zillow.svg";

export interface Customer {
  logo: string;
  url: string;
}

export const airbnb: Customer = { logo: logoAirbnb, url: "//airbnb.com" };
export const airteam: Customer = { logo: logoAirteam, url: "//airteam.com.au" };
export const arm: Customer = { logo: logoArm, url: "//arm.com" };
export const atlassian: Customer = { logo: logoAtlassian, url: "//atlassian.com" };
export const barnardos: Customer = { logo: logoBarnardos, url: "http://barnardos.org.uk" };
export const bcg: Customer = { logo: logoBcg, url: "//www.bcg.com" };
export const careship: Customer = { logo: logoCareship, url: "//careship.de" };
export const codeForAmerica: Customer = { logo: logoCodeForAmerica, url: "//codeforamerica.org" };
export const csiro: Customer = { logo: logoCsiro, url: "//csiro.au" };
export const deloitte: Customer = { logo: logoDeloitte, url: "//deloitte.com" };
export const elsevier: Customer = { logo: logoElsevier, url: "//elsevier.com" };
export const enigma: Customer = { logo: logoEnigma, url: "//enigma.swiss/en" };
export const esri: Customer = { logo: logoEsri, url: "//esri.com" };
export const freshworks: Customer = { logo: logoFreshworks, url: "//freshworks.com" };
export const ftw: Customer = { logo: logoFtw, url: "//ftw.nyc" };
export const harvard: Customer = { logo: logoHarvard, url: "//harvard.edu" };
export const hotelsCombined: Customer = { logo: logoHotelsCombined, url: "//hotelscombined.com" };
export const ibm: Customer = { logo: logoIbm, url: "//ibm.com" };
export const ideo: Customer = { logo: logoIdeo, url: "//ideo.com" };
export const kickstand: Customer = { logo: logoKickstand, url: "http://kickstand.design" };
export const maersk: Customer = { logo: logoMaersk, url: "//maersk.com" };
export const monotype: Customer = { logo: logoMonotype, url: "//monotype.com" };
export const mozilla: Customer = { logo: logoMozilla, url: "//mozilla.com" };
export const nike: Customer = { logo: logoNike, url: "//nike.com" };
export const nswGovernment: Customer = { logo: logoNswGovernment, url: "//nsw.gov.au" };
export const nubank: Customer = { logo: logoNubank, url: "//nubank.com.br" };
export const ocado: Customer = { logo: logoOcado, url: "//ocado.com" };
export const pearson: Customer = { logo: logoPearson, url: "//pearson.com" };
export const remax: Customer = { logo: logoRemax, url: "//remax.com" };
export const rbs: Customer = { logo: logoRbs, url: "//rbs.com" };
export const rmit: Customer = { logo: logoRmit, url: "//rmit.edu.au" };
export const salesforce: Customer = { logo: logoSalesforce, url: "//salesforce.com" };
export const schibsted: Customer = { logo: logoSchibsted, url: "//schibsted.com/" };
export const scout24: Customer = { logo: logoScout24, url: "//scout24.ch" };
export const seek: Customer = { logo: logoSeek, url: "//seek.com" };
export const shopify: Customer = { logo: logoShopify, url: "//shopify.com" };
export const skillsoft: Customer = { logo: logoSkillsoft, url: "//skillsoft.com" };
export const spotify: Customer = { logo: logoSpotify, url: "//spotify.com" };
export const ucSanDiego: Customer = { logo: logoUcSanDiego, url: "//ucsd.edu" };
export const uniqa: Customer = { logo: logoUniqa, url: "http://uniqagroup.com" };
export const weightWatchers: Customer = { logo: logoWeightWatchers, url: "//weightwatchers.com" };
export const westpac: Customer = { logo: logoWestpac, url: "//westpac.com.au" };
export const wework: Customer = { logo: logoWework, url: "//wework.com" };
export const zillow: Customer = { logo: logoZillow, url: "//zillow.com" };
