import LogoAirteam from "@heydovetail/website/components/icons/customers/LogoAirteam";
import LogoArm from "@heydovetail/website/components/icons/customers/LogoArm";
import LogoAtlassian from "@heydovetail/website/components/icons/customers/LogoAtlassian";
import LogoBarnardos from "@heydovetail/website/components/icons/customers/LogoBarnardos";
import LogoBcg from "@heydovetail/website/components/icons/customers/LogoBcg";
import LogoCareship from "@heydovetail/website/components/icons/customers/LogoCareship";
import LogoCodeForAmerica from "@heydovetail/website/components/icons/customers/LogoCodeForAmerica";
import LogoCsiro from "@heydovetail/website/components/icons/customers/LogoCsiro";
import LogoDeloitte from "@heydovetail/website/components/icons/customers/LogoDeloitte";
import LogoElsevier from "@heydovetail/website/components/icons/customers/LogoElsevier";
import LogoEnigma from "@heydovetail/website/components/icons/customers/LogoEnigma";
import LogoFreshworks from "@heydovetail/website/components/icons/customers/LogoFreshworks";
import LogoFtw from "@heydovetail/website/components/icons/customers/LogoFtw";
import LogoHarvard from "@heydovetail/website/components/icons/customers/LogoHarvard";
import LogoHotelscombined from "@heydovetail/website/components/icons/customers/LogoHotelscombined";
import LogoIbm from "@heydovetail/website/components/icons/customers/LogoIbm";
import LogoIdeo from "@heydovetail/website/components/icons/customers/LogoIdeo";
import LogoKickstand from "@heydovetail/website/components/icons/customers/LogoKickstand";
import LogoMonotype from "@heydovetail/website/components/icons/customers/LogoMonotype";
import LogoMozilla from "@heydovetail/website/components/icons/customers/LogoMozilla";
import LogoNike from "@heydovetail/website/components/icons/customers/LogoNike";
import LogoNswGovernment from "@heydovetail/website/components/icons/customers/LogoNswGovernment";
import LogoNubank from "@heydovetail/website/components/icons/customers/LogoNubank";
import LogoOcado from "@heydovetail/website/components/icons/customers/LogoOcado";
import LogoPearson from "@heydovetail/website/components/icons/customers/LogoPearson";
import LogoRbs from "@heydovetail/website/components/icons/customers/LogoRbs";
import LogoRmit from "@heydovetail/website/components/icons/customers/LogoRmit";
import LogoSchibsted from "@heydovetail/website/components/icons/customers/LogoSchibsted";
import LogoScout24 from "@heydovetail/website/components/icons/customers/LogoScout24";
import LogoSeek from "@heydovetail/website/components/icons/customers/LogoSeek";
import LogoSpotify from "@heydovetail/website/components/icons/customers/LogoSpotify";
import LogoUcSanDiego from "@heydovetail/website/components/icons/customers/LogoUcSanDiego";
import LogoUniqa from "@heydovetail/website/components/icons/customers/LogoUniqa";
import LogoWestpac from "@heydovetail/website/components/icons/customers/LogoWestpac";
import LogoZillow from "@heydovetail/website/components/icons/customers/LogoZillow";
import React from "react";

export interface Customer {
  logo: React.ReactNode;
  url: string;
}

export const airteam: Customer = { logo: <LogoAirteam />, url: "https://airteam.com.au" };
export const arm: Customer = { logo: <LogoArm />, url: "https://arm.com" };
export const atlassian: Customer = { logo: <LogoAtlassian />, url: "https://atlassian.com" };
export const barnardos: Customer = { logo: <LogoBarnardos />, url: "http://barnardos.org.uk" };
export const bcg: Customer = { logo: <LogoBcg />, url: "http://bcg.com" };
export const careship: Customer = { logo: <LogoCareship />, url: "https://careship.de" };
export const codeForAmerica: Customer = { logo: <LogoCodeForAmerica />, url: "https://codeforamerica.org" };
export const csiro: Customer = { logo: <LogoCsiro />, url: "https://csiro.au" };
export const deloitte: Customer = { logo: <LogoDeloitte />, url: "https://deloitte.com" };
export const elsevier: Customer = { logo: <LogoElsevier />, url: "https://elsevier.com" };
export const enigma: Customer = { logo: <LogoEnigma />, url: "https://enigma.swiss/en" };
export const freshworks: Customer = { logo: <LogoFreshworks />, url: "https://freshworks.com" };
export const ftw: Customer = { logo: <LogoFtw />, url: "https://ftw.nyc" };
export const harvard: Customer = { logo: <LogoHarvard />, url: "https://harvard.edu" };
export const hotelscombined: Customer = { logo: <LogoHotelscombined />, url: "https://hotelscombined.com" };
export const ibm: Customer = { logo: <LogoIbm />, url: "https://ibm.com" };
export const ideo: Customer = { logo: <LogoIdeo />, url: "https://ideo.com" };
export const kickstand: Customer = { logo: <LogoKickstand />, url: "http://kickstand.design" };
export const monotype: Customer = { logo: <LogoMonotype />, url: "https://monotype.com" };
export const mozilla: Customer = { logo: <LogoMozilla />, url: "https://mozilla.com" };
export const nike: Customer = { logo: <LogoNike />, url: "https://nike.com" };
export const nswGovernment: Customer = { logo: <LogoNswGovernment />, url: "https://nsw.gov.au" };
export const nubank: Customer = { logo: <LogoNubank />, url: "https://nubank.com.br" };
export const ocado: Customer = { logo: <LogoOcado />, url: "https://ocado.com" };
export const pearson: Customer = { logo: <LogoPearson />, url: "https://pearson.com" };
export const rbs: Customer = { logo: <LogoRbs />, url: "https://rbs.com" };
export const rmit: Customer = { logo: <LogoRmit />, url: "https://rmit.edu.au" };
export const schibsted: Customer = { logo: <LogoSchibsted />, url: "https://schibsted.com/" };
export const scout24: Customer = { logo: <LogoScout24 />, url: "https://scout24.ch" };
export const seek: Customer = { logo: <LogoSeek />, url: "https://seek.com" };
export const spotify: Customer = { logo: <LogoSpotify />, url: "https://spotify.com" };
export const ucSanDiego: Customer = { logo: <LogoUcSanDiego />, url: "https://ucsd.edu" };
export const uniqa: Customer = { logo: <LogoUniqa />, url: "http://uniqagroup.com" };
export const westpac: Customer = { logo: <LogoWestpac />, url: "https://www.westpac.com.au" };
export const zillow: Customer = { logo: <LogoZillow />, url: "https://www.zillow.com" };
