import LogoArm from "@heydovetail/website/components/icons/customers/LogoArm";
import LogoAtlassian from "@heydovetail/website/components/icons/customers/LogoAtlassian";
import LogoCodeForAmerica from "@heydovetail/website/components/icons/customers/LogoCodeForAmerica";
import LogoCsiro from "@heydovetail/website/components/icons/customers/LogoCsiro";
import LogoDeloitte from "@heydovetail/website/components/icons/customers/LogoDeloitte";
import LogoElsevier from "@heydovetail/website/components/icons/customers/LogoElsevier";
import LogoEnigma from "@heydovetail/website/components/icons/customers/LogoEnigma";
import LogoFreshworks from "@heydovetail/website/components/icons/customers/LogoFreshworks";
import LogoFtw from "@heydovetail/website/components/icons/customers/LogoFtw";
import LogoHarvard from "@heydovetail/website/components/icons/customers/LogoHarvard";
import LogoIbm from "@heydovetail/website/components/icons/customers/LogoIbm";
import LogoIdeo from "@heydovetail/website/components/icons/customers/LogoIdeo";
import LogoMonotype from "@heydovetail/website/components/icons/customers/LogoMonotype";
import LogoMozilla from "@heydovetail/website/components/icons/customers/LogoMozilla";
import LogoNike from "@heydovetail/website/components/icons/customers/LogoNike";
import LogoNswGovernment from "@heydovetail/website/components/icons/customers/LogoNswGovernment";
import LogoNubank from "@heydovetail/website/components/icons/customers/LogoNubank";
import LogoRbs from "@heydovetail/website/components/icons/customers/LogoRbs";
import LogoSeek from "@heydovetail/website/components/icons/customers/LogoSeek";
import LogoUcSanDiego from "@heydovetail/website/components/icons/customers/LogoUcSanDiego";
import LogoUniqa from "@heydovetail/website/components/icons/customers/LogoUniqa";
import LogoWestpac from "@heydovetail/website/components/icons/customers/LogoWestpac";
import LogoZillow from "@heydovetail/website/components/icons/customers/LogoZillow";
import React from "react";

export const arm = <LogoArm />;
export const atlassian = <LogoAtlassian />;
export const codeForAmerica = <LogoCodeForAmerica />;
export const csiro = <LogoCsiro />;
export const deloitte = <LogoDeloitte />;
export const elsevier = <LogoElsevier />;
export const enigma = <LogoEnigma />;
export const freshworks = <LogoFreshworks />;
export const ftw = <LogoFtw />;
export const harvard = <LogoHarvard />;
export const ibm = <LogoIbm />;
export const ideo = <LogoIdeo />;
export const monotype = <LogoMonotype />;
export const mozilla = <LogoMozilla />;
export const nike = <LogoNike />;
export const nswGovernment = <LogoNswGovernment />;
export const nubank = <LogoNubank />;
export const rbs = <LogoRbs />;
export const seek = <LogoSeek />;
export const ucSanDiego = <LogoUcSanDiego />;
export const uniqa = <LogoUniqa />;
export const westpac = <LogoWestpac />;
export const zillow = <LogoZillow />;
